### ISSUE TITLE
Auto scroll of page.

### ISSUE THREAD

**Issue by nagolove** [memetrooper/TEXTREME#16]
Please add auto scrolling of text page when cursor reach bottom edge of editor window.
![Screenshot from 2019-06-28 13-46-52](https://user-images.githubusercontent.com/12562619/60337506-f0356800-99ab-11e9-9803-202e821e5033.png)
![Screenshot from 2019-06-28 13-47-26](https://user-images.githubusercontent.com/12562619/60337508-f0356800-99ab-11e9-80a0-c19ea28a1851.png)

**Comment by benjhar** [comment]
This issue is now fixed and needs closing
Edit: nevermind

**Comment by maksloboda** [comment]
Its not fixed yet, proposed fix caused cursor to get stuck unable to go up
